class AssignmentOnString
{
public static void main(String[] args)
{
String firstName="viji";
System.out.println(firstName);
String lastName="S";
System.out.println(lastName);
String dob="August 3";
System.out.println(dob);
String birthyear="2002 ";
System.out.println(birthyear);
String nativePlace="Gopala colony";
System.out.println(nativePlace);
String education="B.E in CSE";
System.out.println(education);
String collegeName="AIT,Chikmagaluru";
System.out.println(collegeName);
String CGPA="eight";
System.out.println(CGPA);
String schoolName="MDRS";
System.out.println(schoolName);
String PUCollege="MDRPU";
System.out.println(PUCollege);
String fatherName="ShreeRam";
System.out.println(fatherName);
String motherName="Mahadevamma";
System.out.println(motherName);
String brotherName="Kiran Kumar";
System.out.println(brotherName);
String aboutFamily="A happy and nuclear family of 4 members. I have an elder brother.";
System.out.println(aboutFamily);
String address="Gopala Colony,Gopala post";
System.out.println(address);
String taluq="Tarikere";
System.out.println(taluq);
String district="Chikmagaluru";
System.out.println(district);
String state="karnataka";
System.out.println(state);
String citizenship="Indian";
System.out.println(citizenship);
String introduction=" A passionate and dedicated graduate searching for entry level opportunities in a good organization";
System.out.println(introduction);
String finalYearProject="Vitamin Deficiency Detection Using Image Processing";
System.out.println(finalYearProject);
String internship1=" SAP tool";
System.out.println(internship1);
String internship2="CVAT tool";
System.out.println(internship2);
String algorithmUsed="Convolution Neural Network";
System.out.println("algorithm Used:"+algorithmUsed);
String maritalStatus="unmarried";
System.out.println("marital Status:"+maritalStatus);
String skills="c, java,python";
System.out.println("skills:"+skills);
String toolsKnown="VScode,power point,word";
System.out.println("toolsKnown:"+toolsKnown);
String hobbies="cooking,novel reading, watching kdrama";
System.out.println("hobbies:"+hobbies);
String favouriteMovie="12th fail,dada,kaatera";
System.out.println("favouriteMovie:"+favouriteMovie);
String trainee="java trainee at Xworkz";
System.out.println(trainee);
String trainerName="Omkar";
System.out.println("trainer Name:"+trainerName);
String institutionAdress="bhasyam circle, Rajajinagar";
System.out.println("institution Adress:"+institutionAdress);
String favHero="Rakshith Shetty,Leeminho";
System.out.println(favHero);
String dreamCountry="South Korea";
System.out.println("dreamCountry:"+dreamCountry);
String favHeroine="genelia";
System.out.println(favHeroine);
String currerntLocation="maagadi road daasarahalli,Bangalore" ;
System.out.println(currerntLocation);
String gender="female";
System.out.println(gender);
String email ="vijayalakshmigs0@gmail.com";
System.out.println(email);
String university = "VTU";
System.out.println(university);
String graduationYear = "2024";
System.out.println("graduationYear:"+graduationYear);
String grade = "A";
System.out.println("grade:"+grade);
String languages = "English, kannada";
System.out.println("languages:"+languages);
String objective="To secure an entry-level position in software development where I can apply my programming skills and problem-solving abilities to contribute to innovative projects and grow my career in the tech industry.";
System.out.println(objective);
String Certifications="Basics of C programming, datatypes in Great learning";
System.out.println(Certifications);
String carrierGoal="software developer";
System.out.println(carrierGoal);
String favBook="Ends with us";
System.out.println(favBook);
String willingnessToRelocate="yes";
System.out.println(willingnessToRelocate);
String summaryOfExperience="Fresher,actively searching for jobs";
System.out.println(summaryOfExperience);
String passion="cooking";
System.out.println(passion);
String favKdrama="all of us are dead";
System.out.println(favKdrama);
String favFood="Momos";
System.out.println(favFood);
String bankBalance="2k";
System.out.println("bankBalance:"+bankBalance);
String weekDays="there are seven days in a week";
System.out.println(weekDays);
String day1="Sunday";
System.out.println(day1);
String day2="Monday";
System.out.println(day2);
String day3="Tuesday";
System.out.println(day3);
String day4="wednesday";
System.out.println(day4);
String day5=" Thursday";
System.out.println(day5);
String day6="Friday";
System.out.println(day6);
String day7="Saturday";
System.out.println(day7);
String monthsInYear=" There are 12 months in a year";
System.out.println(monthsInYear);
String month1="january";
System.out.println(month1);
String month2="february";
System.out.println(month2);
String month3="March";
System.out.println(month3);
String month4="April";
System.out.println(month4);
String month5="May";
System.out.println(month5);
String month6="June";
System.out.println(month6);
String month7="July";
System.out.println(month7);
String month8="August";
System.out.println(month8);
String month9="September";
System.out.println(month9);
String month10="October";
System.out.println(month10);
String month11="November";
System.out.println(month11);
String month12="December";
System.out.println(month12);
String motherTongue="Kannada";
System.out.println(motherTongue);
String pointOfInterest="Designer";
System.out.println(pointOfInterest);


System.out.println("Concatenation of strings");
String friends="I have 6 best friends";
System.out.println(friends);
String friend1="Sapnaz banu";
System.out.println(friend1);
String friend2="Sanjana S";
System.out.println(friend2);
String friend3="Gagana K R";
System.out.println(friend3);
String friend4="Vidyashree";
System.out.println(friend4);
String friend5="Srinivas R";
System.out.println(friend5);
String friend6="Pragathi C U";
System.out.println(friend6);
String totalFriends=friend1+friend2+friend3+friend4+friend5+friend6;
System.out.println("totalFriends:"+totalFriends);
String twoFriends=friend1+friend2;
System.out.println("twoFriends:"+twoFriends);
String presentMonth="present month is"+month6;
System.out.println(presentMonth);
String week="week"+weekDays;
System.out.println(week);
String twoMoreFriends=friend3+friend5;
System.out.println("twoMoreFriends"+twoMoreFriends);
String price ="price"+" of"+ "fruits:";
System.out.println(price);
String orangeP="80"+"Rs";
System.out.println(orangeP);
String bananaP="60Rs"+"per"+"kg";
System.out.println(bananaP);
String watermelonP="40Rs"+"per"+"kg";
System.out.println(watermelonP);
String addition="+";
System.out.println("addition:"+addition);
String minus="-";
System.out.println("minus:"+minus);
String multiplication="*";
System.out.println("multiplication:"+multiplication);
String division="/";
System.out.println("division:"+division);
String percentage="%";
System.out.println("percentage:"+percentage);
String arithmeticSymbols=addition+minus+multiplication+division+percentage;
System.out.println("arithmeticSymbols:"+arithmeticSymbols);
String nationalBird="national bird of India is"+"peacock";
System.out.println(nationalBird);
String nationalAnimal="Tiger";
System.out.println("nationalAnimal:"+nationalAnimal);
String cm="siddharamayya";
System.out.println(cm);
String president="draupadi murmuri";
System.out.println("president:"+president);
String cmName=cm+"name is"+state;
System.out.println(cmName);
String birthday=dob+birthyear;
System.out.println(birthday);
String school=schoolName+"bavikere";
System.out.println("school:"+school);
String lang="mother tongue is"+motherTongue;
System.out.println(lang);
String months=monthsInYear;
System.out.println(months);
String monthInfo="They are"+month1+month2+month3+month4+month5+month6+month7+month8+month9+month10+month11+month12;
System.out.println(monthInfo);
String priceOfOrange=orangeP+"per"+"kg";
System.out.println(priceOfOrange);
String skillset=skills+toolsKnown;
System.out.println("skillset:"+skillset);
String weekend=day7+day1;
System.out.println("weekend:"+weekend);
String kannadaMovie="kaanthaara";
System.out.println(kannadaMovie);
String recentMovie="recent movie is"+kannadaMovie;
System.out.println(recentMovie);
String combo=favBook+favFood;
System.out.println(combo+"are my favorite");
String sapnasfavfood="palav"+"And"+"chitranna";
System.out.println(sapnasfavfood);
String vidyasfavfood="chicken biriyani"+"kabab";
System.out.println(vidyasfavfood);
String renusfavfood="mutton biriyani"+"fish kabab";
System.out.println(renusfavfood);
String friendsFavFood=sapnasfavfood+vidyasfavfood+renusfavfood;
System.out.println(friendsFavFood);
String chappal="belt slipper";
System.out.println(chappal);
String beating="my mom uses"+chappal+"to beat me";
System.out.println(beating);
String lipstick="lakme";
System.out.println("lipstick:"+lipstick);
String lipstickCost="300 Rs";
System.out.println("lipstickCost"+lipstickCost);
String colour="red";
System.out.println("colour:"+colour);
String favFruit="watermelon";
System.out.println(favFruit);
String myFavFruit="my favourite fruit is"+favFruit;
System.out.println("myFavFruit:"+myFavFruit);
String parents=fatherName+"and"+motherName;
System.out.println("parents:"+parents);
String objectiveInfo="my objective is"+objective;
System.out.println(objectiveInfo);
String result=grade+graduationYear;
System.out.println("result"+result);
String mixer="preethi";
System.out.println(mixer);
String mixerAtMyHome="mixer used in my home is"+mixer;
System.out.println(mixerAtMyHome);
String favColour="my favourite colour is"+colour;
System.out.println(favColour);
String footwearBrand="bata";
System.out.println(footwearBrand);
String footwear="Brand"+"is"+footwearBrand;
System.out.println(footwear);
String fullName=firstName+lastName;
System.out.println("fullName"+fullName);
String brother ="my brother name is"+brotherName;
System.out.println(brother);
String currentState=  "for now"+summaryOfExperience;
System.out.println(currentState);
String fanBrand="usha";
System.out.println(fanBrand);

String fan="we use"+fanBrand+"fan";
System.out.println(fan);

String fanInfo="In our home  we have 4 fans"+fan;
System.out.println(fanInfo);

String internship=internship1+internship2;
System.out.println("internship:"+internship);

String actors=favHero+favHeroine;
System.out.println("actors"+actors);

String favCricketer="Virat Kohli";
System.out.println(favCricketer);

String cricketer="My favourite cricketer is"+favCricketer;
System.out.println(cricketer);

String doctorname="Hemanth M S";
System.out.println("doctorname:"+doctorname);

String dtype="cardiologist";
System.out.println("area:"+dtype);

String doctor=doctorname+"is"+dtype;
System.out.println(doctor);

String song="my favourite song is of"+favHero;
System.out.println("song:"+song);

String phoneNumber="9591529036";
System.out.println("phoneNumber"+phoneNumber);

String alternativeNumber="8792894093";
System.out.println("alternativeNumber"+alternativeNumber);

String contact="you can contact me using"+phoneNumber+"or"+alternativeNumber;
System.out.println(contact);
System.out.println("THANK YOU");





}
}